### PR TITLE
Members only

### PR DESCRIPTION
**Pull request by marcelomaidden**
## Members only
At this pull request we create:
- User authentication using Devise to work with cookies and sessions
- Post controller and models
- Post views using Devise to retrieve the current user

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
# Project marked Invalid.

## Hello team,

**I mark this project as invalid because of the incorrect use of the gitflow. You should open a pull request based on the development branch and not the master branch. ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/git_flow_requirement.png) from pathwright).**

**Happy coding 😃.**

**PS: You can reach me on slack (Rose Wanjohi).**

**Comment by voscarmv** [comment]
Hi team. When you switch Pull Requests, please always remember to add a link to the new Pull Request being used from your old Pull Request.

In this case, this PR should at least contain a comment linking to the new PR: https://github.com/jcy2704/members-only/pull/2

**Comment by voscarmv** [comment]
It's definitely preferable for you to actually use the URL of the new PR when requesting a new Code Review in the Microverse dashboard. But in this case, linking to the new PR will suffice.

**Comment by marcelomaidden** [comment]
PR #2 - New Pull Request

**Pull request closed without merging**
